spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: true
    hibernate:
        ddl-auto: create-drop

  datasource:
    platform: "postgres"
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/recipebook"
    username: "postgres"
    password: "Control.123"
    initialization-mode: always

#management:
#  health:
#    db.enabled: true # Enable database health check.
#    defaults.enabled: true # Enable default health indicators.
#    diskspace.enabled: true # Enable disk space health check.

server:
  port: 8888
